name: ðŸ Build deps
on:
  workflow_dispatch:
  push:
    paths:
    - 'qgis_deps/**'
    - '.github/workflows/deps.yml'
  release:
    types: [ published ]

env:
  MODULE: qgis_deps
  QGIS_DEPS_RELEASE_VERSION: "dev"
  APPLE_CODE_SIGN_IDENTITY: ${{ secrets.APPLE_CODE_SIGN_IDENTITY }}
  PACKAGES_OUTPUT: ${{ github.workspace }}
  SOURCE_PACKAGES_PATH: ${{ github.workspace }}/deps/.packages
  CACHE_PATH: ${{ github.workspace }}/deps/build
  QGIS_PRIVATE_SDKS_PATH: ${{ github.workspace }}/qgis-private-sdks
  QGIS_PRIVATE_SDK_VERSION: "0.10"
  CACHE_VERSION: 6


jobs:
  qgis_deps_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set deps version for release
        if: github.event_name == 'release'
        # v1.2-0 => 1.2 https://regex101.com/r/tZBVLT/1
        run: |
          QGIS_DEPS_SDK_VERSION=$(echo ${{ github.event.release.tag_name }} | sed -r 's/v?([0-9]+(\.[0-9]+)*)(-.+)?/\1/')
          QGIS_DEPS_RELEASE_VERSION=$(echo "${QGIS_DEPS_SDK_VERSION}" | sed -r 's/^([0-9]+\.[0-9]+).*$/\1/')
          QGIS_DEPS_RELEASE_VERSION_PATCH=$(echo "${QGIS_DEPS_SDK_VERSION}" | sed -r 's/^[0-9]+\.[0-9]+\.([0-9]+)?$/\1/')
          echo "Release deps version: ${QGIS_DEPS_RELEASE_VERSION}"
          echo "Release deps patch: ${QGIS_DEPS_RELEASE_VERSION_PATCH}"
          echo "QGIS_DEPS_RELEASE_VERSION=${QGIS_DEPS_RELEASE_VERSION}" >> $GITHUB_ENV

          cp qgis_deps/config/deps-dev.conf qgis_deps/config/deps-${QGIS_DEPS_RELEASE_VERSION}.conf
          sed -i '' "s/QGIS_DEPS_RELEASE_VERSION=.*/QGIS_DEPS_RELEASE_VERSION=${QGIS_DEPS_RELEASE_VERSION}/" qgis_deps/config/deps-${QGIS_DEPS_RELEASE_VERSION}.conf
          sed -i '' "s/QGIS_DEPS_RELEASE_VERSION_PATCH=.*/QGIS_DEPS_RELEASE_VERSION_PATCH=${QGIS_DEPS_RELEASE_VERSION_PATCH}/" qgis_deps/config/deps-${QGIS_DEPS_RELEASE_VERSION}.conf
          
          git add qgis_deps/config/deps-${QGIS_DEPS_RELEASE_VERSION}.conf
          git commit -m "Add deps config file for version ${QGIS_DEPS_RELEASE_VERSION}"
          git push

      - name: Set environment
        run: |
          source qgis_deps/config/deps-${QGIS_DEPS_RELEASE_VERSION}.conf
          echo "ROOT_OUT_PATH=${ROOT_OUT_PATH}" >> $GITHUB_ENV
          echo "DEPS_BUILD_PATH=${DEPS_BUILD_PATH}" >> $GITHUB_ENV
          echo "STAGE_PATH=${STAGE_PATH}" >> $GITHUB_ENV
          echo "PACKAGES_PATH=${PACKAGES_PATH}" >> $GITHUB_ENV
          echo "VERSION_QT=${VERSION_QT}" >> $GITHUB_ENV
          mkdir -p ${SOURCE_PACKAGES_PATH}
          mkdir -p ${CACHE_PATH}
          sudo mkdir -p ${ROOT_OUT_PATH}
          echo "VERSIONS_CONF_MD5=$(md5 -r qgis_deps/versions.conf | cut -d\  -f1)" >> $GITHUB_ENV

      - name: Cache build
        id: cache-build
        uses: pat-s/always-upload-cache@v3
        with:
          path: ${{ env.CACHE_PATH }}
          key: cache-qgis-deps-build-${{ env.CACHE_VERSION }}-${{ env.QGIS_DEPS_RELEASE_VERSION }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            cache-qgis-deps-build-${{ env.CACHE_VERSION }}-${{ env.QGIS_DEPS_RELEASE_VERSION }}-
            cache-qgis-deps-build-${{ env.CACHE_VERSION }}-dev-
            cache-qgis-deps-build-${{ env.CACHE_VERSION }}-

      - name: Move cache build
        run: |
          sudo mv ${{ env.CACHE_PATH }} ${{ env.ROOT_OUT_PATH }}
          echo "***"
          echo "ROOT_OUT_PATH: ${ROOT_OUT_PATH}"
          echo ""
          ls ${ROOT_OUT_PATH}
          echo ""
          echo "***"
          echo "DEPS_BUILD_PATH: ${DEPS_BUILD_PATH}"
          echo ""
          ls ${DEPS_BUILD_PATH}
          echo ""
          echo "***"
          echo "STAGE_PATH: ${STAGE_PATH}"
          echo ""
          ls ${STAGE_PATH}
          echo ""
          echo "***"

          sudo mkdir -p ${DEPS_BUILD_PATH}


      - name: Cache packages
        id: cache-packages
        uses: pat-s/always-upload-cache@v3
        with:
          path: ${{ env.SOURCE_PACKAGES_PATH }}
          key: cache-qgis-deps-packages-${{ env.QGIS_DEPS_RELEASE_VERSION }}-${{ env.VERSIONS_CONF_MD5 }}
          restore-keys: |
            cache-qgis-deps-packages-${{ env.QGIS_DEPS_RELEASE_VERSION }}-
            cache-qgis-deps-packages-dev-
            cache-qgis-deps-packages-

      - name: Fetch QGIS private SDK
        run: |
          FILE="private-sdk.tar.gz"
          PARSER=". | map(select(.tag_name == \"${{ env.QGIS_PRIVATE_SDK_VERSION }}\"))[0].assets | map(select(.name == \"$FILE\"))[0].id"
          ASSET_ID=$(curl -H "Authorization: token ${{ secrets.GH_PAT }}" -H "Accept: application/vnd.github.v3.raw" -s https://api.github.com/repos/qgis/qgis-private-sdks/releases | jq "${PARSER}")
          echo "asset id: ${ASSET_ID}"
          wget -q --auth-no-challenge --header='Accept:application/octet-stream' https://${{ secrets.GH_PAT }}:@api.github.com/repos/qgis/qgis-private-sdks/releases/assets/${ASSET_ID} -O ${FILE}
          mkdir ${{ env.QGIS_PRIVATE_SDKS_PATH }}
          cd ${{ env.QGIS_PRIVATE_SDKS_PATH }}
          tar xzf ../${FILE}

      - run: brew install python3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          dir: ${{ github.workspace }}
          setup-python: 'false'
          version: '5.15.2'
          host: 'mac'
          target: 'desktop'

      - name: move Qt to /opt
        run: |
          sudo mkdir -p /opt/Qt
          sudo mv ${{ github.workspace }}/Qt /opt

      - name: install brew deps
        run: ./scripts/install_brew_dev_packages.bash

      - name: build qgis_deps
        run: |
          cd qgis_deps
          sudo -E ./distribute.sh ${{ env.QGIS_DEPS_RELEASE_VERSION }} -m${{ env.MODULE }}
        timeout-minutes: 300

      - name: log
        if: failure()
        run: cat ${DEPS_BUILD_PATH}/last-build.log

      - name: move build to cache dir if build failed
        if: failure()
        run: |
          sudo rm ${DEPS_BUILD_PATH}/last-build.log || true
          sudo mv ${{ env.DEPS_BUILD_PATH }} ${{ env.CACHE_PATH }}
          sudo chown -R $(whoami) ${{ env.CACHE_PATH }}

      - name: create package
        run: |
          cd qgis_deps
          sudo -E ./create_package.bash ${{ env.QGIS_DEPS_RELEASE_VERSION }}
          
      - name: move build to cache dir
        run: |
          sudo rm ${DEPS_BUILD_PATH}/last-build.log || true
          sudo mv ${{ env.ROOT_OUT_PATH }} ${{ env.CACHE_PATH }}
          sudo chown -R $(whoami) ${{ env.CACHE_PATH }}

      - uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}

      - name: signing deps
        run: |
          cd qgis_deps
          sudo -E ./sign_deps.bash ${{ env.QGIS_DEPS_RELEASE_VERSION }}

      - name: upload Qt archive
        uses: actions/upload-artifact@v2
        with:
          name: Qt
          path: qt-${{ env.VERSION_QT }}.tar.gz

      - name: upload QGIS deps
        uses: actions/upload-artifact@v2
        with:
          name: qgis-deps-${{ env.QGIS_DEPS_RELEASE_VERSION }}
          path: qgis-deps-${{ env.QGIS_DEPS_SDK_VERSION }}.tar.gz
